name: Build V2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: class02_02
      - name: Lint
        run: npm run lint
        working-directory: class02_02

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: class02_02
      - name: Test code
        run: npm run test
        working-directory: class02_02

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: class02_02
      - name: Build code
        run: npm run build
        working-directory: class02_02
      - name: Deploy code
        run: echo "Deploying..."
        working-directory: class02_02
